use llmgw::clients::{self, ClientKind, ModelMetadata, ProfileRequest, Protocol};
use std::{collections::BTreeMap,fs,path::PathBuf,os::unix::fs::PermissionsExt};
struct Fixture(PathBuf);
impl Fixture {
 fn new(name:&str)->Self {let p=std::env::temp_dir().join(format!("quality-{}-{}",name,std::process::id()));fs::create_dir(&p).unwrap();fs::set_permissions(&p,fs::Permissions::from_mode(0o700)).unwrap();Self(p)}
 fn request(&self,kind:ClientKind)->ProfileRequest {let (version,protocol)=match kind{ClientKind::Pi=>("0.84.2",Protocol::OpenAiCompletions),ClientKind::Codex=>("0.154.0",Protocol::OpenAiResponses),ClientKind::Claude=>("2.1.63",Protocol::AnthropicMessages)};ProfileRequest{client:kind,installed_version:version.into(),config_dir:self.0.join("native"),config_dir_source:"owned quality fixture".into(),project_local:None,gateway_origin:"http://127.0.0.1:4141".into(),gateway_fingerprint:"a".repeat(64),root:"shared-work".into(),model:"example-model".into(),protocol,local_data_token:format!("synthetic-quality-local-{}",std::process::id()),token_source:self.0.join("state/data-token"),journal_path:self.0.join("state/client.journal.json"),set_default:false,discover_models:false,metadata:ModelMetadata::unknown(),effective_environment:BTreeMap::new(),managed_settings:vec![]}}
 fn existing(&self,kind:ClientKind)->PathBuf {let (name,bytes)=match kind{ClientKind::Pi=>("models.json","{\"providers\":{},\"keep\":true}"),ClientKind::Codex=>("llmgw.config.toml","# preserved\nkeep = true\n"),ClientKind::Claude=>("settings.json","{\"env\":{\"KEEP\":\"yes\"}}")};let dir=self.0.join("native");fs::create_dir(&dir).unwrap();fs::set_permissions(&dir,fs::Permissions::from_mode(0o700)).unwrap();let p=dir.join(name);fs::write(&p,bytes).unwrap();fs::set_permissions(&p,fs::Permissions::from_mode(0o600)).unwrap();p}
}
impl Drop for Fixture {fn drop(&mut self){for d in [self.0.join("state"),self.0.join("native")] {if d.exists(){let _=fs::set_permissions(d,fs::Permissions::from_mode(0o700));}}fs::remove_dir_all(&self.0).unwrap();}}
fn retired_after_preview(kind:ClientKind){let f=Fixture::new(kind.as_str());let target=f.existing(kind);let mut r=f.request(kind);let first=clients::prepare(&r).unwrap();clients::apply_reviewed(&first,&first.preview().hash).unwrap();let written=fs::read(&target).unwrap();r.model="second-model".into();let reviewed=clients::prepare(&r).unwrap();clients::disconnect(&r.journal_path).unwrap();fs::write(&target,&written).unwrap();assert!(clients::prepare(&r).is_err(),"fresh plan must reject retired ownership");let valid=clients::validate_current_snapshot(&reviewed).is_ok();let accepted=clients::apply_reviewed(&reviewed,&reviewed.preview().hash).is_ok();let changed=fs::read(&target).unwrap()!=written;println!("fresh_prepare_refused=true stale_snapshot_accepted={valid} stale_apply_accepted={accepted} user_bytes_changed={changed}");assert!(!valid && !accepted && !changed,"retiring the connection after review must invalidate prepared ownership before activation/write");}
#[test] fn pi_retired_journal_after_preview_refuses_recreated_value(){retired_after_preview(ClientKind::Pi)}
#[test] fn codex_retired_journal_after_preview_refuses_recreated_value(){retired_after_preview(ClientKind::Codex)}
#[test] fn claude_journal_write_failure_before_restore_preserves_and_retries(){let f=Fixture::new("journal-failure");let target=f.existing(ClientKind::Claude);let r=f.request(ClientKind::Claude);let p=clients::prepare(&r).unwrap();clients::apply_reviewed(&p,&p.preview().hash).unwrap();let client_before=fs::read(&target).unwrap();let journal_before=fs::read(&r.journal_path).unwrap();let parent=r.journal_path.parent().unwrap();fs::set_permissions(parent,fs::Permissions::from_mode(0o500)).unwrap();let failed=clients::disconnect(&r.journal_path);assert!(failed.is_err(),"journal publication must fail in unwritable parent");assert!(fs::read(&target).unwrap()==client_before,"client unchanged before initial journal publication");assert!(fs::read(&r.journal_path).unwrap()==journal_before,"journal unchanged after initial failure");fs::set_permissions(parent,fs::Permissions::from_mode(0o700)).unwrap();let report=clients::disconnect(&r.journal_path).unwrap();assert!(report.conflicts.is_empty());assert!(!fs::read_to_string(target).unwrap().contains(&r.local_data_token));println!("initial_journal_publication_failed=true client_unchanged=true journal_unchanged=true retry_restored=true");}
#[test] fn claude_resource_failure_records_partial_and_retry_preserves_unowned(){let f=Fixture::new("resource-failure");let target=f.existing(ClientKind::Claude);let r=f.request(ClientKind::Claude);let p=clients::prepare(&r).unwrap();clients::apply_reviewed(&p,&p.preview().hash).unwrap();let before=fs::read(&target).unwrap();let parent=target.parent().unwrap();fs::set_permissions(parent,fs::Permissions::from_mode(0o500)).unwrap();assert!(clients::disconnect(&r.journal_path).is_err());assert!(fs::read(&target).unwrap()==before);assert_eq!(llmgw::config_patch::inspect_journal(&r.journal_path).unwrap().status,llmgw::config_patch::journal::JournalStatus::RestorePartial);fs::set_permissions(parent,fs::Permissions::from_mode(0o700)).unwrap();let report=clients::disconnect(&r.journal_path).unwrap();assert!(report.conflicts.is_empty());let restored=fs::read_to_string(target).unwrap();assert!(restored.contains("KEEP") && !restored.contains(&r.local_data_token));println!("resource_publication_failed=true restore_partial_recorded=true client_unchanged=true retry_restored=true");}
#[test] fn normal_owned_reconnect_and_disconnect_controls(){for kind in [ClientKind::Pi,ClientKind::Codex,ClientKind::Claude]{let f=Fixture::new(kind.as_str());let target=f.existing(kind);let mut r=f.request(kind);let p=clients::prepare(&r).unwrap();clients::apply_reviewed(&p,&p.preview().hash).unwrap();r.model="second-model".into();let p=clients::prepare(&r).unwrap();clients::validate_current_snapshot(&p).unwrap();clients::apply_reviewed(&p,&p.preview().hash).unwrap();assert!(fs::read_to_string(&target).unwrap().contains("second-model"));assert!(clients::disconnect(&r.journal_path).unwrap().conflicts.is_empty());assert!(!fs::read_to_string(target).unwrap().contains(&r.local_data_token));}}
