use llmgw::clients::{self,ClientKind,ModelMetadata,ProfileRequest,ProjectLocalApproval,Protocol};
use std::{collections::BTreeMap,fs,path::{Path,PathBuf},os::unix::fs::{PermissionsExt,symlink},process::Command};
struct Fixture(PathBuf);
impl Fixture { fn new(name:&str)->Self {let p=std::env::temp_dir().join(format!("native-task4-spec-{}-{}",name,std::process::id()));fs::create_dir(&p).unwrap();fs::set_permissions(&p,fs::Permissions::from_mode(0o700)).unwrap();Self(p)} fn file(&self,s:&str,b:&str)->PathBuf { let p=self.0.join(s);fs::create_dir_all(p.parent().unwrap()).unwrap();fs::write(&p,b).unwrap();fs::set_permissions(&p,fs::Permissions::from_mode(0o600)).unwrap();p} }
impl Drop for Fixture {fn drop(&mut self){fs::remove_dir_all(&self.0).unwrap();}}
fn request(f:&Fixture)->ProfileRequest {ProfileRequest {client:ClientKind::Claude,installed_version:"2.1.63".into(),config_dir:f.0.join("home/.claude"),config_dir_source:"synthetic fixture".into(),project_local:None,gateway_origin:"http://127.0.0.1:4141".into(),gateway_fingerprint:"a".repeat(64),root:"shared-work".into(),model:"example-model".into(),protocol:Protocol::AnthropicMessages,local_data_token:"synthetic-spec-local-token".into(),token_source:f.0.join("state/data-token"),journal_path:f.0.join("state/claude.journal.json"),set_default:true,discover_models:false,metadata:ModelMetadata::unknown(),effective_environment:BTreeMap::new(),managed_settings:vec![]}}
fn git(p:&Path,args:&[&str])->bool{Command::new("git").args(args).current_dir(p).env_clear().env("PATH","/usr/bin:/bin").env("HOME",p).env("GIT_CONFIG_NOSYSTEM","1").env("GIT_CONFIG_GLOBAL","/dev/null").status().unwrap().success()}
#[test] fn shared_settings_via_native_directory_must_be_refused(){let f=Fixture::new("shared-native");let target=f.file("project/.claude/settings.json","{}");let project=f.0.join("project");assert!(git(&project,&["init","-q"]));assert!(git(&project,&["add",".claude/settings.json"]));assert!(git(&project,&["ls-files","--error-unmatch",".claude/settings.json"]));let mut r=request(&f);r.config_dir=target.parent().unwrap().to_path_buf();r.config_dir_source="CLAUDE_CONFIG_DIR environment".into();let plan=clients::prepare(&r);if let Ok(p)=&plan {clients::apply_reviewed(p,&p.preview().hash).unwrap();assert!(fs::read_to_string(&target).unwrap().contains("synthetic-spec-local-token"));println!("CONFIRMED: synthetic local token written into Git-tracked .claude/settings.json through native directory override");} assert!(plan.is_err(),"Git-shared Claude settings must be refused even when selected as native config directory");}
#[test] fn project_settings_parent_symlink_must_be_refused(){let f=Fixture::new("parent-symlink");let project=f.0.join("project");fs::create_dir(&project).unwrap();assert!(git(&project,&["init","-q"]));let actual=project.join("private-settings");fs::create_dir(&actual).unwrap();fs::set_permissions(&actual,fs::Permissions::from_mode(0o700)).unwrap();fs::write(project.join(".gitignore"),"private-settings/\n.claude/\n").unwrap();symlink(&actual,project.join(".claude")).unwrap();let mut r=request(&f);r.project_local=Some(ProjectLocalApproval {directory:project,user_private_confirmed:true,untracked_confirmed:true});let plan=clients::prepare(&r);if let Ok(p)=&plan {clients::apply_reviewed(p,&p.preview().hash).unwrap();println!("CONFIRMED: project-local settings written through symlinked .claude directory");} assert!(plan.is_err(),"symlinked project-local settings directory must be refused");}
#[test] fn unrelated_private_claude_settings_are_preserved_and_reversible(){let f=Fixture::new("claude-positive");let target=f.file("home/.claude/settings.json",r#"{"env":{"KEEP":"yes","ANTHROPIC_CUSTOM_HEADERS":"X-Example: keep"}}"#);let r=request(&f);let p=clients::prepare(&r).unwrap();assert!(!p.preview().text.contains("synthetic-spec-local-token"));clients::apply_reviewed(&p,&p.preview().hash).unwrap();let data=fs::read_to_string(&target).unwrap();assert!(data.contains("X-Example: keep"));assert!(data.contains("llmgw-local-only"));let report=clients::disconnect(&r.journal_path).unwrap();assert!(report.conflicts.is_empty());assert!(!fs::read_to_string(&target).unwrap().contains("llmgw"));}

#[test] fn owned_provider_reconnect_user_change_and_retired_journal_boundaries(){
 for (kind,version,protocol,path) in [(ClientKind::Pi,"0.84.2",Protocol::OpenAiCompletions,"models.json"),(ClientKind::Codex,"0.154.0",Protocol::OpenAiResponses,"llmgw.config.toml")] {
  let f=Fixture::new(kind.as_str());let mut r=request(&f);r.client=kind;r.installed_version=version.into();r.protocol=protocol;r.set_default=false;
  let first=clients::prepare(&r).unwrap();clients::apply_reviewed(&first,&first.preview().hash).unwrap();
  let reconnect=clients::prepare(&r).unwrap();clients::apply_reviewed(&reconnect,&reconnect.preview().hash).unwrap();
  let target=r.config_dir.join(path);let owned=fs::read_to_string(&target).unwrap();fs::write(&target,owned.replace("127.0.0.1:4141","127.0.0.1:4142")).unwrap();
  assert!(clients::prepare(&r).is_err());let restored=clients::disconnect(&r.journal_path).unwrap();assert!(!restored.conflicts.is_empty());
  fs::write(&target,&owned).unwrap();assert!(clients::prepare(&r).is_err(),"a conflicted/restored journal cannot reauthorize a recreated identical provider");
 }
}
#[test] fn composite_hash_and_snapshot_checks_precede_activation(){
 let f=Fixture::new("hash");let r=request(&f);let p=clients::prepare(&r).unwrap();
 assert!(clients::validate_reviewed_hash(&p,&"0".repeat(64)).is_err());
 let mut different=r.clone();different.gateway_fingerprint="b".repeat(64);let other=clients::prepare(&different).unwrap();assert_ne!(p.preview().hash,other.preview().hash);
 f.file("home/.claude/settings.json","{\"userAdded\":true}");assert!(clients::validate_current_snapshot(&p).is_err());assert!(!r.journal_path.exists());
}
